### ISSUE TITLE
he asks to register after registering, but this is /login (but why is he asking for it after registering)

### ISSUE THREAD

**Issue by F3F5** [HaHaWTH/AuthMeReReloaded#113]
### What behaviour is observed?

![Screenshot_2](https://github.com/HaHaWTH/AuthMeReReloaded/assets/108226177/7093269a-ec4d-4b6b-bbbc-9413789af99d)

### Expected behaviour

.

### To Reproduce

registered alt account

### Plugin list

pl
[04:26:29 INFO]: Bukkit Plugins: (2):
[04:26:29 INFO]: - AuthMe, spark

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

[04:26:38 INFO]: Version: AuthMeReloaded v5.6.0-FORK (build: 44)

### Error log (if applicable)

.

### Configuration

default

**Comment by HaHaWTH** [comment]
Weird, try turn on registerAutoLogin and test again if the bug still exists:/

**Comment by HaHaWTH** [comment]
Try this build :) https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8446475213

**Comment by HaHaWTH** [comment]
Wait.....dependency relocation caused the bug????

**Comment by HaHaWTH** [comment]
Fixed, there are two conditions will cause this bug:
1.(Fixed) Turned on the forceLoginAfterRegister
2.(Fixed) (Upstream) Multiple players register at the same time(throw exceptions)

**Comment by F3F5** [comment]
Leaf

> Fixed, there are two conditions will cause this bug: 1.(Fixed) Turned on the forceLoginAfterRegister 2.(Fixed) (Upstream) Multiple players register at the same time(throw exceptions)



> Weird, try turn on registerAutoLogin and test again if the bug still exists:/ btw what is the server software and server version you are using? spigot or Folia?

**Comment by F3F5** [comment]
@HaHaWTH it's not fixed 

[13:06:31 INFO]: VortexL[/94.43.243.214:56286] logged in with entity id 238 at ([world]-731.3000000119209, 66.25521960176278, 1847.8668123717039)

[13:06:41 INFO]: [AuthMe] VortexL logged in
[13:06:41 INFO]: [AuthMe] VortexL registered 
[13:06:45 INFO]: VortexL lost connection: Disconnected
[13:06:48 INFO]: UUID of player MIKO is a69aa52f-4e24-345d-b211-7a284bbf47ce
[13:06:49 INFO]: MIKO[/] logged in with entity id 464 at ([world]-739.5, 78.0, 131.5)
[13:06:54 INFO]: [AuthMe] MIKO registered 
[13:06:57 INFO]: [AuthMe] MIKO logged in 

just need first create 1 account and after, all
reset your authme folder to test

**Comment by F3F5** [comment]
this is build https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8448242379

**Comment by F3F5** [comment]
original authme tested and i dont see bugs

**Comment by F3F5** [comment]
put a clean server on 1.20.4 (I used leaf) and put authme there, then register 1 account and then log in with a different name and register - bug
I did not use foce-login or anything else, I have a default configuration of fork

**Comment by F3F5** [comment]
i think it's bug after adding folia support
[b43](https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b43) seems good

**Comment by HaHaWTH** [comment]
> i think it's bug after adding folia support
> [b43](https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b43) seems good

Try this?https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8450308764

**Comment by F3F5** [comment]
> > i think it's bug after adding folia support
> > [b43](https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b43) seems good
> 
> Try this?https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8450308764

same

**Comment by HaHaWTH** [comment]
> > > i think it's bug after adding folia support
> > > [b43](https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b43) seems good
> > 
> > 
> > Try this?https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8450308764
> 
> same

How about trying the Paper 1.12.2/1.20.4? This can't be reproduced on it.

**Comment by F3F5** [comment]
> > > > i think it's bug after adding folia support
> > > > [b43](https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b43) seems good
> > > 
> > > 
> > > Try this?https://github.com/HaHaWTH/AuthMeReReloaded/actions/runs/8450308764
> > 
> > 
> > same
> 
> How about trying the Paper 1.12.2/1.20.4? This can't be reproduced on it.

do you have a discord?

**Comment by F3F5** [comment]
> put a clean server on 1.20.4 (I used leaf) and put authme there, then register 1 account and then log in with a different name and register - bug I did not use foce-login or anything else, I have a default configuration of fork

Have you checked the bug?

**Comment by HaHaWTH** [comment]
> > put a clean server on 1.20.4 (I used leaf) and put authme there, then register 1 account and then log in with a different name and register - bug I did not use foce-login or anything else, I have a default configuration of fork
> 
> Have you checked the bug?

Yes, I am using Leaf 1.20.4, sqlite backend, but this still can't be reproduced.
My Discord: https://discord.gg/9n5nyBfq

**Comment by HaHaWTH** [comment]
Finally fixed, thx a lot!
